# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iyCBicFkoXwcZQPYwquvQWEqfm2skmSZ
"""



"""lists in python"""

fruit=["apple","mango","orange","guava","banana"]
print(fruit)



fruit=["apple","mango","orange","guava","banana"]
print(fruit[0])
print(fruit[0:4])
print(fruit[0:3])
print(fruit[-1])
print(fruit[:2])
print(fruit[1:])
print(fruit[2:])
print(fruit[-2:])
print(fruit[:])

"""Append,len,replace,remove,replace techniques"""

fruit=["apple","mango","orange","guava","banana"]
fruit[1]="dragon fruit"
fruit[2:4]=["Gitam"]
fruit.remove('apple')
print(fruit)
print(len(fruit))
print(type(fruit))

"""looping in list
insert
append
reverse
customise sort
ascending
descending
pop
delete
clear

"""

last = ["burger","ferrari","harley davidson"]
for x in last:
  print(x)
fan=['gm','havells','ashok']
for x in range(len(fan)):
  print(fan[x])
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)
bike=[4,43,322,912379,192837]
bike.sort()
bike.sort(reverse=True)
bike.reverse
print(bike)
car=['BMW','BENZ','AUDI','RRR','RR','BUGATI','TVS','LAMBO','BENTLY','PORSCHE','KOENIGSEGG','FERRARI','ASTON MARTIN']
car=car.copy()
print(car)
def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)